version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - ollama

  frontend:
    build: ./ # <-- ajuste aqui, se você tiver a pasta separada
    ports:
      - '3000:3000' # <-- expõe corretamente a porta do Next.js
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama:
