version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - ollama
      - db

  frontend:
    build: ./
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  ollama:
  pgdata:
